version: "3"
services:
  proxy:
    container_name: "proxy"
    build:
      context: "./proxy/"
      dockerfile: "Dockerfile"
    ports:
      - "443:443"
  rstudio:
    container_name: "rstudio"
    build:
      context: "./rstudio/"
      dockerfile: "Dockerfile"
    environment:
      - EVALUATION_ID=9614774
    ports:
      - "8787:8787"
    volumes:
      - ../minidream-challenge:/shared
      - homes:/home

volumes:
  homes: {}
